### ISSUE TITLE
look up function not working? How can I check this whether due to my configuration.

### ISSUE THREAD

**Issue by bayindir-mustafa** [OptimiliaStudios/AquileReader#18]

**Comment by ac-lap** [comment]
Are you still facing this issue, we had released a fix in the last update. Also, to note the dictionary support is only for English language text.

**Comment by OptimiliaStudios** [comment]
Are you still facing this issue, we had released a fix in the last update. Also, to note the dictionary support is only for English language text.

**Comment by bay-33** [comment]
Hello,
in the latest store version (1.0.32) it is not solved.  I did not see a 
release in MS store.

------ Original Message ------

**Comment by OptimiliaStudios** [comment]
Can you plz provide steps on how to repro the issue, a screen recording while you repro would be of great help.

**Comment by bay-33** [comment]
is this attachment sufficient.

On May 5, 2021 at 7:17 PM, OptimiliaStudios ***@***.***> wrote:






Can you plz provide steps on how to repro the issue, a screen recording while you repro would be of great help.

**Comment by OptimiliaStudios** [comment]
@bay-33 unfortunately I don't see any attachment.

**Comment by bay-33** [comment]
Hello trying with a different file.

------ Original Message ------
From: "OptimiliaStudios" ***@***.***>
To: "OptimiliaStudios/AquileReader" ***@***.***>
Cc: "bay-33" ***@***.***>; "Mention" 
***@***.***>
Sent: 6.05.2021 07:19:51
Subject: Re: [OptimiliaStudios/AquileReader] look up function not 
working? How can I check this whether due to my configuration. (#18)

>
***@***.*** <https://github.com/bay-33> unfortunately I don't see any

**Comment by OptimiliaStudios** [comment]
Hi, I have still don't see any attachment here or in the mail.

**Comment by bay-33** [comment]
> Hi, I have still don't see any attachment here or in the mail.
This is my simple recording. I hope this time u will see :)

https://app.box.com/s/dnosms7f456xdn81u9kh3u5qpa4regtl
