### ISSUE TITLE
Going back to main text from notes

### ISSUE THREAD

**Issue by SamyakSahu** [OptimiliaStudios/AquileReader#19]
When I click on a reference mentioned in the text, the app jumps to the page where the notes are written.

But coming back from the notes section (which are mentioned towards the end of the book) to the section I just left is a manual and a very tedious process. I have to rummage through the entire book manually to find where I last left it.

Perhaps a 'peek' feature (like what Wikipedia has) or a back button when you're on the notes page would be very helpful.

**Comment by ac-lap** [comment]
The app does have a back button which appears (on top left) when clicking on any links within the book.
We did found an issue with it, which we fixed and will go out in next release. But you can share the book the repro details if you want, so that we can ensure the fix also addresses the issue you are facing, optimilia.studios@gmail.com

**Comment by OptimiliaStudios** [comment]
The app does have a back button which appears (on top left) when clicking on any links within the book.
We did found an issue with it, which we fixed and will go out in next release. But you can share the book the repro details if you want, so that we can ensure the fix also addresses the issue you are facing, optimilia.studios@gmail.com

**Comment by OptimiliaStudios** [comment]
Closing this issue as the known bug has been fixed from our end. Plz feel free to re-activate it your are still facing the issue.
