### ISSUE TITLE
'Error occured while reading'  when trying to use tts on books

### ISSUE THREAD

**Issue by tammyT06** [OptimiliaStudios/AquileReader#39]
I'm getting 'Error occured while reading' message when trying to use the TTS feature.
I'm getting the UI of it but when hitting play the message repeats.

**Comment by OptimiliaStudios** [comment]
Is it happening with all books or only some books, also can you share some screenshots when you get the error? Also, plz share the logs by following the steps here - https://aquilereader.wordpress.com/how-to/#collect-logs

**Comment by tammyT06** [comment]
As far as I can see its with all books. Screenshot is also in the file.
[TTS bug Aquile.zip](https://github.com/OptimiliaStudios/AquileReader/files/6535292/TTS.bug.Aquile.zip)

**Comment by OptimiliaStudios** [comment]
Can you try out the steps listed here and see if it helps
https://aquilereader.wordpress.com/text-to-speech-voice/

**Comment by tammyT06** [comment]
I did, and I reinstalled the speech pack but i still get the same error even when I change to another voices of different packs in the app.

**Comment by OptimiliaStudios** [comment]
1. What edition of Windows do you have? Is it by any chance N SKU? https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808
2. Are you able to use Text to Speech functionality with any of the other Windows Store apps?
3. Does this preview voice play anything for you? 
![image](https://user-images.githubusercontent.com/67598009/120834023-1bedff00-c580-11eb-8d8b-11de5efbf020.png)

The reason I am asking all these questions is because the TTS library of windows is giving file not found exception, which indicates your Windows installation does not have media player components are available.

**Comment by tammyT06** [comment]
1. 20h2
3. Yesterday none of the voices of the American English(Zira, Mark, David) pack worked all others did. Today they work and so does the TTS on the reader. The only thing I did in the meantime was restart the PC but I had one that already multiple times after the problem occurred. The problem vanished for me.
2. Don't know about when the error occurred but right now the Text to Speech TTS app works,

**Comment by OptimiliaStudios** [comment]
Great! Then I will add restart PC as one of the steps in the TSG.
Thanks for your assistance, will resolve this issue.
