### ISSUE TITLE
Inappropriate advertisements

### ISSUE THREAD

**Issue by idrisshamsi101** [OptimiliaStudios/AquileReader#42]
I have been using Aquile Reader to read ebooks on my PC for months and months and it has been quite efficient compared to other ebook readers. My only complaint is that I strongly disapprove of the advertisements that appear at the bottom of your screen when you open a book as they are distracting, misleading and very inappropriate. Please remove them at once so that me and other people will continue to appreciate the app and its benefits.

I have inserted a screenshot of the issue below (please be aware that the issue has applied to all the books I have and that the source of the books is not responsible for the issue as even the default books that appeared in my library when I downloaded Aquile Reader have had the same issue):

![image](https://user-images.githubusercontent.com/84679646/119270760-3edaf380-bc0f-11eb-8568-12845ecfadcc.png)

**Comment by OptimiliaStudios** [comment]
Thanks for reaching out. We understand your concern, but you also need to understand that the app needs to be monetized in order to sustain the development of the app and so that devs can earn their livelihood. Ads are never liked by anyone but it helps keep the app free for most users and supports the development process.
And you can always buy the premium version of the app and remove Ads. Steps on how to upgrade can be found here - https://aquilereader.wordpress.com/how-to/#premium
