### ISSUE TITLE
Manybooks, Smashwords and Feedbooks missing

### ISSUE THREAD

**Issue by glientsc** [OptimiliaStudios/AquileReader#75]
I installed Aquile Reader on my new computer (v1.1.10) and bought the license. 
In contrast to the installation on my old computer (v1.1.5), Manybooks, Smashwords and Feedbooks are missing from the Online Books overview. I only see Gutenberg, Standard Ebooks and EpubBooks. Would like to have the others as well.
Kind regards, G.

**Comment by OptimiliaStudios** [comment]
Hi @glientsc ,
Thanks for reaching out. Due to compliance issues with Microsoft store, in the first few runs on new installation we do not show Manybooks, Smashwords and Feedbooks sites. You can close the app and start it again, after 2-3 starts we show the sites.

This behavior is by design, as these sites support paid purchase of the books and Microsoft Store does not allow that. To by-pass that we had to do this workaround :)

**Comment by glientsc** [comment]
Indeed they showed up. Thank you for the explanation, the quick answer, and the workaround! :-)
